### ISSUE TITLE
No Version Number Tagged

### ISSUE THREAD

**Issue by briandotdev** [jameslkingsley/nova-stripe-theme#1]
Composer fails install because it can't find a version number tagged.

`[InvalidArgumentException]
  Could not find a matching version of package jameslkingsley/nova-stripe-theme. Check the package spelling, your version constraint and
  that the package is available in a stability which matches your minimum-stability (stable).`

**Comment by jameslkingsley** [comment]
I just tagged a release and updated Packagist, try now.

**Comment by briandotdev** [comment]
Works like a charm.  Love the theme!
