### ISSUE TITLE
Resource groups & logo text color

### ISSUE THREAD

**Issue by vmitchell85** [jameslkingsley/nova-stripe-theme#2]
Great theme... found a few things missing with the new updates:

- resource group names color
- `logo.blade.php` text color

It's a little hard to see but here is a screenshot:
![image](https://user-images.githubusercontent.com/1248035/46076949-24e66b80-c15d-11e8-9235-1cc197482564.png)

**Comment by zagreusinoz** [comment]
For anyone else having this issue just add this to the body of your layout.blade.php file until the pull request is merged.

```
<style>
        .bg-grad-sidebar h3, .bg-grad-sidebar h4, .bg-grad-sidebar h3 span, .bg-grad-sidebar a {
            color: var(--black);
            font-weight: 600;
            font-size: 14px;
        }
    </style>
```

**Comment by phoenixg** [comment]
@zagreusinoz When the pull request is merged?

**Comment by vmitchell85** [comment]
It seems the PR opened by @zagreusinoz has been merged... I'm closing this issue.
